'use client'

import { useState } from 'react'
import { Plus, Download, Share2, Mail, MessageSquare, Copy, FileText, Calendar, Trash2, Lock, LockIcon } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Badge } from '@/components/ui/badge'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { useApp } from '@/contexts/AppContext'
import { useProjectAuth } from '@/contexts/ProjectAuthContext'
import { toast } from '@/hooks/use-toast'

interface Report {
  id: string
  projectId: string
  projectName: string
  type: 'PV_Visite' | 'PV_Constat'
  title: string
  description: string
  createdAt: string
}

interface ProjectWithPassword {
  id: string
  name: string
  password?: string
}

export function Reports() {
  const { t } = useApp()
  const { isProjectUnlocked, unlockProject } = useProjectAuth()

  const projects: ProjectWithPassword[] = []

  const [reports, setReports] = useState<Report[]>([])

  const [showCreateDialog, setShowCreateDialog] = useState(false)
  const [showDeleteDialog, setShowDeleteDialog] = useState(false)
  const [showPasswordDialog, setShowPasswordDialog] = useState(false)
  const [reportToDelete, setReportToDelete] = useState<Report | null>(null)
  const [projectToUnlock, setProjectToUnlock] = useState<ProjectWithPassword | null>(null)
  const [passwordInput, setPasswordInput] = useState('')
  const [formData, setFormData] = useState({
    projectId: '',
    type: 'PV_Visite' as 'PV_Visite' | 'PV_Constat',
    title: '',
    description: '',
  })

  const handleCreateReport = () => {
    const project = projects.find(p => p.id === formData.projectId)
    const newReport: Report = {
      id: Date.now().toString(),
      projectId: formData.projectId,
      projectName: project?.name || 'Unknown Project',
      type: formData.type,
      title: formData.title,
      description: formData.description,
      createdAt: new Date().toISOString(),
    }

    setReports([newReport, ...reports])
    setShowCreateDialog(false)
    setFormData({ projectId: '', type: 'PV_Visite', title: '', description: '' })
    toast({
      title: t('success'),
      description: 'Report created successfully',
    })
  }

  const handleExportPDF = (report: Report) => {
    // Generate PDF content
    const pdfContent = `
BINACORE CONSTRUCTION REPORT
============================

${report.type === 'PV_Visite' ? 'PV DE VISITE' : 'PV DE CONSTAT'}

Report Title: ${report.title}
Project: ${report.projectName}
Date: ${new Date(report.createdAt).toLocaleString()}

DESCRIPTION:
${report.description}

---
Generated by BinaCore
    `.trim()

    // Create blob and download
    const blob = new Blob([pdfContent], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${report.title.replace(/\s+/g, '_')}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)

    toast({
      title: t('success'),
      description: 'Report exported successfully',
    })
  }

  const handleShareWhatsApp = (report: Report) => {
    const text = encodeURIComponent(
      `📋 ${report.type === 'PV_Visite' ? 'PV DE VISITE' : 'PV DE CONSTAT'}\n\n📝 ${report.title}\n🏗️ ${report.projectName}\n📅 ${new Date(report.createdAt).toLocaleString()}\n\n${report.description}`
    )
    window.open(`https://wa.me/?text=${text}`, '_blank')
  }

  const handleShareEmail = (report: Report) => {
    const subject = encodeURIComponent(`[BinaCore] ${report.title}`)
    const body = encodeURIComponent(
      `Project: ${report.projectName}\nDate: ${new Date(report.createdAt).toLocaleString()}\n\nDescription:\n${report.description}`
    )
    window.open(`mailto:?subject=${subject}&body=${body}`)
  }

  const handleCopyReport = (report: Report) => {
    const text = `📋 ${report.type === 'PV_Visite' ? 'PV DE VISITE' : 'PV DE CONSTAT'}\n\n📝 ${report.title}\n🏗️ ${report.projectName}\n📅 ${new Date(report.createdAt).toLocaleString()}\n\n${report.description}`
    navigator.clipboard.writeText(text)
    toast({
      title: t('success'),
      description: 'Report copied to clipboard',
    })
  }

  const handleDeleteReport = () => {
    if (!reportToDelete) return
    
    setReports(reports.filter(report => report.id !== reportToDelete.id))
    setShowDeleteDialog(false)
    setReportToDelete(null)
    toast({
      title: t('success'),
      description: 'Report deleted successfully',
    })
  }

  const confirmDeleteReport = (report: Report) => {
    setReportToDelete(report)
    setShowDeleteDialog(true)
  }

  const getReportTypeBadge = (type: string) => {
    return type === 'PV_Visite' ? (
      <Badge className="bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300">{t('pvVisite')}</Badge>
    ) : (
      <Badge className="bg-orange-100 text-orange-700 dark:bg-orange-900 dark:text-orange-300">{t('pvConstat')}</Badge>
    )
  }

  const isReportUnlocked = (report: Report) => {
    const project = projects.find(p => p.id === report.projectId)
    return isProjectUnlocked(report.projectId, project?.password)
  }

  const handleUnlockProject = () => {
    if (!projectToUnlock) return

    if (unlockProject(projectToUnlock.id, projectToUnlock.password, passwordInput)) {
      setShowPasswordDialog(false)
      setPasswordInput('')
      setProjectToUnlock(null)
      toast({
        title: t('success'),
        description: t('projectUnlockedSuccess'),
      })
    } else {
      toast({
        title: t('error'),
        description: t('incorrectPassword'),
        variant: 'destructive',
      })
    }
  }

  const requestUnlockProject = (report: Report) => {
    const project = projects.find(p => p.id === report.projectId)
    if (project) {
      setProjectToUnlock(project)
      setShowPasswordDialog(true)
      setPasswordInput('')
    }
  }

  return (
    <div className="space-y-6 pb-24">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-foreground">{t('reports')}</h1>
          <p className="text-muted-foreground mt-1">Generate and manage project reports</p>
        </div>
        <Button onClick={() => setShowCreateDialog(true)} className="gap-2">
          <Plus className="w-5 h-5" />
          {t('createReport')}
        </Button>
      </div>

      {/* Reports List */}
      <div className="space-y-4">
        {reports.map((report) => {
          const unlocked = isReportUnlocked(report)
          const project = projects.find(p => p.id === report.projectId)
          const isProtected = project?.password

          return (
            <Card key={report.id} className={`shadow-sm ${!unlocked && isProtected ? 'opacity-60' : ''}`}>
              <CardContent className="p-6">
                <div className="flex items-start justify-between gap-4">
                  <div className="flex items-start gap-4 flex-1">
                    <div className={`p-3 rounded-lg ${!unlocked && isProtected ? 'bg-muted/50' : 'bg-primary/10'}`}>
                      {!unlocked && isProtected ? (
                        <LockIcon className="w-6 h-6 text-muted-foreground" />
                      ) : (
                        <FileText className="w-6 h-6 text-primary" />
                      )}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-2 flex-wrap">
                        <h3 className="font-semibold text-foreground">{report.title}</h3>
                        {unlocked && getReportTypeBadge(report.type)}
                        {isProtected && (
                          <Badge variant="secondary" className="gap-1">
                            <LockIcon className="w-3 h-3" />
                            {unlocked ? t('projectUnlocked') : t('projectProtected')}
                          </Badge>
                        )}
                      </div>
                      {unlocked ? (
                        <>
                          <p className="text-sm text-muted-foreground mb-2">{report.description}</p>
                          <div className="flex items-center gap-4 text-xs text-muted-foreground">
                            <div className="flex items-center gap-1">
                              <Calendar className="w-3 h-3" />
                              <span>{new Date(report.createdAt).toLocaleString()}</span>
                            </div>
                            <span>•</span>
                            <span>{report.projectName}</span>
                          </div>
                        </>
                      ) : (
                        <div className="text-sm text-muted-foreground">
                          <p>This report is protected. Enter the project password to view details.</p>
                          <Button
                            variant="outline"
                            size="sm"
                            className="mt-2 gap-2"
                            onClick={() => requestUnlockProject(report)}
                          >
                            <Lock className="w-4 h-4" />
                            Unlock to View
                          </Button>
                        </div>
                      )}
                    </div>
                  </div>

                  {unlocked && (
                    <div className="flex flex-col gap-2">
                      <Button variant="outline" size="sm" className="gap-2" onClick={() => handleExportPDF(report)}>
                        <Download className="w-4 h-4" />
                        {t('exportPDF')}
                      </Button>
                      <div className="flex gap-2">
                        <Button variant="ghost" size="icon" onClick={() => handleShareWhatsApp(report)} title={t('shareWhatsApp')}>
                          <MessageSquare className="w-4 h-4" />
                        </Button>
                        <Button variant="ghost" size="icon" onClick={() => handleShareEmail(report)} title={t('shareEmail')}>
                          <Mail className="w-4 h-4" />
                        </Button>
                        <Button variant="ghost" size="icon" onClick={() => handleCopyReport(report)} title={t('copyReport')}>
                          <Copy className="w-4 h-4" />
                        </Button>
                        <Button variant="ghost" size="icon" onClick={() => confirmDeleteReport(report)} title={t('delete')} className="text-destructive hover:text-destructive">
                          <Trash2 className="w-4 h-4" />
                        </Button>
                      </div>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          )
        })}
      </div>

      {/* Create Report Dialog */}
      <Dialog open={showCreateDialog} onOpenChange={setShowCreateDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{t('createReport')}</DialogTitle>
            <DialogDescription>Create a new project report</DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label>Project</Label>
              <Select value={formData.projectId} onValueChange={(value) => setFormData({ ...formData, projectId: value })}>
                <SelectTrigger>
                  <SelectValue placeholder="Select project" />
                </SelectTrigger>
                <SelectContent>
                  {projects.map((project) => (
                    <SelectItem key={project.id} value={project.id}>
                      {project.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>Report Type</Label>
              <Select
                value={formData.type}
                onValueChange={(value: 'PV_Visite' | 'PV_Constat') => setFormData({ ...formData, type: value })}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="PV_Visite">{t('pvVisite')}</SelectItem>
                  <SelectItem value="PV_Constat">{t('pvConstat')}</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>{t('reportTitle')}</Label>
              <Input
                placeholder="Enter report title"
                value={formData.title}
                onChange={(e) => setFormData({ ...formData, title: e.target.value })}
              />
            </div>
            <div className="space-y-2">
              <Label>{t('reportDescription')}</Label>
              <Textarea
                placeholder="Enter report description"
                value={formData.description}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                rows={5}
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCreateDialog(false)}>
              {t('cancel')}
            </Button>
            <Button onClick={handleCreateReport}>{t('save')}</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Report Dialog */}
      <Dialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Delete Report</DialogTitle>
            <DialogDescription>
              Are you sure you want to delete this report? This action cannot be undone.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowDeleteDialog(false)}>
              {t('cancel')}
            </Button>
            <Button variant="destructive" onClick={handleDeleteReport}>
              Delete
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Password Verification Dialog */}
      <Dialog open={showPasswordDialog} onOpenChange={setShowPasswordDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{t('enterPassword')}</DialogTitle>
            <DialogDescription>
              This project is protected. Please enter the password to access its reports.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label>{t('projectName')}</Label>
              <Input value={projectToUnlock?.name} disabled />
            </div>
            <div className="space-y-2">
              <Label>{t('projectPassword')} *</Label>
              <Input
                type="password"
                placeholder="Enter project password"
                value={passwordInput}
                onChange={(e) => setPasswordInput(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') {
                    handleUnlockProject()
                  }
                }}
                autoFocus
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowPasswordDialog(false)}>
              {t('cancel')}
            </Button>
            <Button onClick={handleUnlockProject}>
              {t('unlockProject')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
