'use client'

import { useState } from 'react'
import { Plus, Download, Share2, Mail, MessageSquare, Copy, FileText, Calendar, Trash2 } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Badge } from '@/components/ui/badge'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { useApp } from '@/contexts/AppContext'
import { toast } from '@/hooks/use-toast'

interface Report {
  id: string
  projectId: string
  projectName: string
  type: 'PV_Visite' | 'PV_Constat'
  title: string
  description: string
  createdAt: string
}

export function Reports() {
  const { t } = useApp()
  const [reports, setReports] = useState<Report[]>([
    {
      id: '1',
      projectId: '1',
      projectName: 'Residential Tower A',
      type: 'PV_Visite',
      title: 'Weekly Site Visit - Week 4',
      description: 'Regular site inspection conducted on 15th January 2024. All structural works are progressing according to schedule.',
      createdAt: '2024-01-15T14:30:00',
    },
    {
      id: '2',
      projectId: '1',
      projectName: 'Residential Tower A',
      type: 'PV_Constat',
      title: 'Issue Report - Floor 5',
      description: 'Minor cracking observed on floor 5. Recommended reinforcement review and repair work scheduled.',
      createdAt: '2024-01-12T09:15:00',
    },
    {
      id: '3',
      projectId: '2',
      projectName: 'Commercial Complex B',
      type: 'PV_Visite',
      title: 'Foundation Inspection',
      description: 'Foundation work completed and inspected. Ready to proceed with ground floor construction.',
      createdAt: '2024-01-10T11:00:00',
    },
  ])

  const [showCreateDialog, setShowCreateDialog] = useState(false)
  const [showDeleteDialog, setShowDeleteDialog] = useState(false)
  const [reportToDelete, setReportToDelete] = useState<Report | null>(null)
  const [formData, setFormData] = useState({
    projectId: '',
    type: 'PV_Visite' as 'PV_Visite' | 'PV_Constat',
    title: '',
    description: '',
  })

  const projects = [
    { id: '1', name: 'Residential Tower A' },
    { id: '2', name: 'Commercial Complex B' },
    { id: '3', name: 'Villa Project C' },
  ]

  const handleCreateReport = () => {
    const project = projects.find(p => p.id === formData.projectId)
    const newReport: Report = {
      id: Date.now().toString(),
      projectId: formData.projectId,
      projectName: project?.name || 'Unknown Project',
      type: formData.type,
      title: formData.title,
      description: formData.description,
      createdAt: new Date().toISOString(),
    }

    setReports([newReport, ...reports])
    setShowCreateDialog(false)
    setFormData({ projectId: '', type: 'PV_Visite', title: '', description: '' })
    toast({
      title: t('success'),
      description: 'Report created successfully',
    })
  }

  const handleExportPDF = (report: Report) => {
    // Generate PDF content
    const pdfContent = `
BINACORE CONSTRUCTION REPORT
============================

${report.type === 'PV_Visite' ? 'PV DE VISITE' : 'PV DE CONSTAT'}

Report Title: ${report.title}
Project: ${report.projectName}
Date: ${new Date(report.createdAt).toLocaleString()}

DESCRIPTION:
${report.description}

---
Generated by BinaCore
    `.trim()

    // Create blob and download
    const blob = new Blob([pdfContent], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${report.title.replace(/\s+/g, '_')}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)

    toast({
      title: t('success'),
      description: 'Report exported successfully',
    })
  }

  const handleShareWhatsApp = (report: Report) => {
    const text = encodeURIComponent(
      `📋 ${report.type === 'PV_Visite' ? 'PV DE VISITE' : 'PV DE CONSTAT'}\n\n📝 ${report.title}\n🏗️ ${report.projectName}\n📅 ${new Date(report.createdAt).toLocaleString()}\n\n${report.description}`
    )
    window.open(`https://wa.me/?text=${text}`, '_blank')
  }

  const handleShareEmail = (report: Report) => {
    const subject = encodeURIComponent(`[BinaCore] ${report.title}`)
    const body = encodeURIComponent(
      `Project: ${report.projectName}\nDate: ${new Date(report.createdAt).toLocaleString()}\n\nDescription:\n${report.description}`
    )
    window.open(`mailto:?subject=${subject}&body=${body}`)
  }

  const handleCopyReport = (report: Report) => {
    const text = `📋 ${report.type === 'PV_Visite' ? 'PV DE VISITE' : 'PV DE CONSTAT'}\n\n📝 ${report.title}\n🏗️ ${report.projectName}\n📅 ${new Date(report.createdAt).toLocaleString()}\n\n${report.description}`
    navigator.clipboard.writeText(text)
    toast({
      title: t('success'),
      description: 'Report copied to clipboard',
    })
  }

  const handleDeleteReport = () => {
    if (!reportToDelete) return
    
    setReports(reports.filter(report => report.id !== reportToDelete.id))
    setShowDeleteDialog(false)
    setReportToDelete(null)
    toast({
      title: t('success'),
      description: 'Report deleted successfully',
    })
  }

  const confirmDeleteReport = (report: Report) => {
    setReportToDelete(report)
    setShowDeleteDialog(true)
  }

  const getReportTypeBadge = (type: string) => {
    return type === 'PV_Visite' ? (
      <Badge className="bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300">{t('pvVisite')}</Badge>
    ) : (
      <Badge className="bg-orange-100 text-orange-700 dark:bg-orange-900 dark:text-orange-300">{t('pvConstat')}</Badge>
    )
  }

  return (
    <div className="space-y-6 pb-24">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-foreground">{t('reports')}</h1>
          <p className="text-muted-foreground mt-1">Generate and manage project reports</p>
        </div>
        <Button onClick={() => setShowCreateDialog(true)} className="gap-2">
          <Plus className="w-5 h-5" />
          {t('createReport')}
        </Button>
      </div>

      {/* Reports List */}
      <div className="space-y-4">
        {reports.map((report) => (
          <Card key={report.id} className="shadow-sm">
            <CardContent className="p-6">
              <div className="flex items-start justify-between gap-4">
                <div className="flex items-start gap-4 flex-1">
                  <div className="p-3 bg-primary/10 rounded-lg">
                    <FileText className="w-6 h-6 text-primary" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-2">
                      <h3 className="font-semibold text-foreground">{report.title}</h3>
                      {getReportTypeBadge(report.type)}
                    </div>
                    <p className="text-sm text-muted-foreground mb-2">{report.description}</p>
                    <div className="flex items-center gap-4 text-xs text-muted-foreground">
                      <div className="flex items-center gap-1">
                        <Calendar className="w-3 h-3" />
                        <span>{new Date(report.createdAt).toLocaleString()}</span>
                      </div>
                      <span>•</span>
                      <span>{report.projectName}</span>
                    </div>
                  </div>
                </div>

                <div className="flex flex-col gap-2">
                  <Button variant="outline" size="sm" className="gap-2" onClick={() => handleExportPDF(report)}>
                    <Download className="w-4 h-4" />
                    {t('exportPDF')}
                  </Button>
                  <div className="flex gap-2">
                    <Button variant="ghost" size="icon" onClick={() => handleShareWhatsApp(report)} title={t('shareWhatsApp')}>
                      <MessageSquare className="w-4 h-4" />
                    </Button>
                    <Button variant="ghost" size="icon" onClick={() => handleShareEmail(report)} title={t('shareEmail')}>
                      <Mail className="w-4 h-4" />
                    </Button>
                    <Button variant="ghost" size="icon" onClick={() => handleCopyReport(report)} title={t('copyReport')}>
                      <Copy className="w-4 h-4" />
                    </Button>
                    <Button variant="ghost" size="icon" onClick={() => confirmDeleteReport(report)} title={t('delete')} className="text-destructive hover:text-destructive">
                      <Trash2 className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Create Report Dialog */}
      <Dialog open={showCreateDialog} onOpenChange={setShowCreateDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{t('createReport')}</DialogTitle>
            <DialogDescription>Create a new project report</DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label>Project</Label>
              <Select value={formData.projectId} onValueChange={(value) => setFormData({ ...formData, projectId: value })}>
                <SelectTrigger>
                  <SelectValue placeholder="Select project" />
                </SelectTrigger>
                <SelectContent>
                  {projects.map((project) => (
                    <SelectItem key={project.id} value={project.id}>
                      {project.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>Report Type</Label>
              <Select
                value={formData.type}
                onValueChange={(value: 'PV_Visite' | 'PV_Constat') => setFormData({ ...formData, type: value })}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="PV_Visite">{t('pvVisite')}</SelectItem>
                  <SelectItem value="PV_Constat">{t('pvConstat')}</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>{t('reportTitle')}</Label>
              <Input
                placeholder="Enter report title"
                value={formData.title}
                onChange={(e) => setFormData({ ...formData, title: e.target.value })}
              />
            </div>
            <div className="space-y-2">
              <Label>{t('reportDescription')}</Label>
              <Textarea
                placeholder="Enter report description"
                value={formData.description}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                rows={5}
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCreateDialog(false)}>
              {t('cancel')}
            </Button>
            <Button onClick={handleCreateReport}>{t('save')}</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Report Dialog */}
      <Dialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Delete Report</DialogTitle>
            <DialogDescription>
              Are you sure you want to delete this report? This action cannot be undone.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowDeleteDialog(false)}>
              {t('cancel')}
            </Button>
            <Button variant="destructive" onClick={handleDeleteReport}>
              Delete
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
